name: Auto Tag and Docker Build
on:
  push:
    branches:
      - main
      - fix
concurrency: production

jobs:
  Patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Minor version for each merge
        id: AutoTagger
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.ITHUB_TOKEN }}
          WITH_V: false
          DRY_RUN: true     

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: saluteslim/versiontest:${{ steps.AutoTagger.outputs.new_tag }}
          file: ./Dockerfile

      - name: echo new tag
        run: |
          echo "The next tag version will be: ${{ steps.AutoTagger.outputs.new_tag }}"
      - name: echo tag
        run: |
          echo "The current tag is: ${{ steps.AutoTagger.outputs.tag }}"
      - name: echo part
        run: |
          echo "The version increment was: ${{ steps.AutoTagger.outputs.part }}"
